name: news-summarizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi==0.116.1
    - uvicorn==0.34.2
    - streamlit==1.49.1
    - yfinance==0.2.65
    - requests==2.32.2
    - python-dotenv==1.1.0
    - langchain==0.2.1
    - langchain-openai==0.1.7
    - openai==1.84.0
    - pandas==2.3.2
    - numpy==1.26.4
    - beautifulsoup4==4.13.4
    - aiohttp==3.11.18
    - python-multipart==0.0.9
    - jinja2==3.1.4
    - matplotlib==3.9.0
    - plotly==6.3.0
    - newspaper3k==0.2.8
    - nltk==3.8.1
