name: stock-investment-advisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pip
  - numpy=1.26.4
  - pandas=2.3.2
  - matplotlib=3.9.0
  - scikit-learn=1.5.0
  - plotly=6.3.0
  - seaborn=0.13.2
  - pyyaml=6.0.2
  - requests=2.32.2
  - pip:
    - fastapi==0.116.1
    - uvicorn==0.34.2
    - streamlit==1.49.1
    - yfinance==0.2.65
    - httpx==0.28.1
    - python-dotenv==1.1.0
    - openai==1.84.0
    - beautifulsoup4==4.13.4
    - aiohttp==3.11.18
    - python-multipart==0.0.9
    - openpyxl==3.1.4
    - joblib==1.4.2
    - reportlab==4.4.0
    - fpdf2==2.8.4
    - jinja2==3.1.4
    - pathlib==1.0.1
    - python-dateutil==2.9.0.post0
    - pydantic==2.11.5
    - tenacity==8.3.0
    - packaging==24.0
