name: price-predictor
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - pip
  - pip:
    - lightgbm==4.0.0
    - optuna==3.2.0
    - mlflow==2.5.0
    - streamlit==1.25.0
    - plotly==5.15.0
    - seaborn==0.12.2
    - matplotlib==3.7.1
    - pyyaml==6.0
    - requests==2.31.0
    - joblib==1.3.0
    - python-dotenv==1.0.0
