name: 游늵 An치lisis Mensual de Inversi칩n

on:
  schedule:
    # Se ejecuta el primer d칤a de cada mes a las 9:00 AM UTC
    - cron: '0 9 1 * *'
  
  # Permite ejecuci칩n manual
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Forzar ejecuci칩n'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  investment_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: 游끠 Checkout del repositorio
      uses: actions/checkout@v4
      
    - name: 游냀 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
        
    - name: 游닍 Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        # El repositorio stock-investment-advisor tiene requirements.txt en la ra칤z
        pip install -r requirements.txt
        
    - name: 游늵 Ejecutar an치lisis mensual
      env:
        FORCE_RUN: ${{ github.event.inputs.force_run || 'true' }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        # Ejecutar directamente desde la ra칤z del repositorio stock-investment-advisor
        python src/automation/monthly_report.py
        
    - name: 游닇 Generar resumen
      if: always()
      run: |
        echo "## 游늵 An치lisis de Inversi칩n Completado" >> $GITHUB_STEP_SUMMARY
        echo "**Fecha:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Estado:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "**Ejecuci칩n forzada:** ${{ github.event.inputs.force_run || 'auto' }}" >> $GITHUB_STEP_SUMMARY
